all:
  hosts:
    n8n_server:
      ansible_host: 10.30.0.50
      ansible_user: fabioleal
      ansible_ssh_private_key_file: ~/key_client/keybinario
      ansible_python_interpreter: /usr/bin/python3
      
  vars:
    # n8n Configuration
    n8n_port: 5678
    n8n_install_dir: /home/fabioleal/n8n
    n8n_user: admin
    n8n_password: admin123
    
    # Docker Configuration
    docker_compose_version: "2.23.0"
